[package]
name = "agentpay-guard"
version = "0.1.0"
description = "Autonomous Agent Financial Governance and Circuit Breaker Hub on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "agentpay_guard"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.30.1", optional = true }
solana-program = "1.18.26"
